In [1]:
import numpy as np

In [10]:
arr1 = np.array([10,20,30,40,50,60,70,80,90], dtype = 'int8')
print(arr1)

[10 20 30 40 50 60 70 80 90]


numpy Array In-built method and properties

In [11]:
print(arr1)
print(arr1.shape) #rows and coloumns
print(type(arr1))
print(arr1.dtype)  #return data-type
print(arr1.itemsize)
print(arr1.ndim) #dimentianality - 1D
print(arr1.size) #size() - return total size of arra
print(arr1.nbytes) #nbytes = total size of numpy array

[10 20 30 40 50 60 70 80 90]
(9,)
<class 'numpy.ndarray'>
int8
1
1
9
9


Types of Numpy array

In [19]:
#create 1D array
arr2 = np.array([10,15,17,21,23,44,65,89])

#create a 2-D arrar - Matrix
arr3 = np.array([[19,11,13,23],
                 [18,23,54,76],
                 [11,23,54,87]])

#shape returns(rows, coloumns)
print(arr3.shape)
print(arr3.ndim)
print(arr3.itemsize)

#three dimension (3D) array
arr4 = np.array([[[19,11,13,23,45],
                 [18,23,54,76,23],
                 [11,23,54,87,99]],
                 
                 [[12,13,14,15,16],
                 [21,22,23,34,17],
                 [31,32,44,32,18]]])

print(arr4)
print(arr4.shape) #shapes return (metrics, rows, coloumns)
print(arr4.ndim)
print(arr4.itemsize)

        

(3, 4)
2
8
[[[19 11 13 23 45]
  [18 23 54 76 23]
  [11 23 54 87 99]]

 [[12 13 14 15 16]
  [21 22 23 34 17]
  [31 32 44 32 18]]]
(2, 3, 5)
3
8


In [34]:
#slicing & indexing
print(arr3)
print("   ")
print(arr3[0]) #slicing for first rows element
print("")
print(arr3[:,:]) #all rows and columns
print("")
print(arr3[:,0]) #slicing elements from all rows and first columns index
print("")
print(arr3[:,0:2]) #slicing first two columns
print("")
print(arr3[1:-1,1:-1])

[[19 11 13 23]
 [18 23 54 76]
 [11 23 54 87]]
   
[19 11 13 23]

[[19 11 13 23]
 [18 23 54 76]
 [11 23 54 87]]

[19 18 11]

[[19 11]
 [18 23]
 [11 23]]

[[23 54]]


In [36]:
arr4 = np.array([[[19,11,13,23,45],
                 [18,23,54,76,23],
                 [11,23,54,87,99]],
                 
                 [[12,13,14,15,16],
                 [21,22,199,34,17],
                 [31,32,44,32,18]]])
#slicing 3-D numpy array
print(arr4[1,1,2])

199


In [43]:
#create Numpy array using function
arr5 = np.arange(1,51) #create 1-D array
print(arr5)
print("")
arr6 = np.arange(1,51).reshape(2,5,5)
print(arr6)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


In [51]:
#zero matrix : np.zero(shape)
arr7 = np.zeros((5,7),dtype = 'int16')
print(arr7)
print("")
print(arr7.astype('float16')) #type casting from int to float


[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [60]:
arr8 = np.ones((5,5))
print(arr8)
print("")

arr9 = np.identity(5)
print(arr9)

print('')

arr10 = np.empty((6,1))
print(arr10)
#fill all position with 2.0 float value
arr10.fill(2.0)
print(arr10)


print("")
#full
print(np.full(10,6.1))


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[3.47739925e-081]
 [1.50094440e-076]
 [1.66844330e-047]
 [5.40526783e-066]
 [7.25365527e+169]
 [3.46458890e-317]]
[[2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]]

[6.1 6.1 6.1 6.1 6.1 6.1 6.1 6.1 6.1 6.1]


In [68]:
#linspace
#create N evenly spaced array, here N is num of elements
print(np.linspace(10,100,10))


[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [69]:
#logspace - N evenly spaced array elements on a log scale between start and stop (log base 10)

np.logspace(0,1,10,base=10)

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [71]:
#exercise - 1

arr11 = np.full((10,10),1)
arr11[1:-1,1:-1].fill(0)
print(arr11)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [84]:
# Exercise - 2

arr12 = np.full((10,10),1)
arr12[0::2,::2].fill(0)
arr12[1::2,1::2].fill(0)
arr12


array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [88]:
#Mathematical Operations - Numpy Array
arr13 = np.array([[[1,3,5],
                  [4,8,7],
                  [9,11,13]],
                  
                  [[2,4,7],
                   [3,1,5],
                   [5,2,8]]])

print(arr13.sum())

print(arr13.sum(axis = 0))#row wise
print(arr13.sum(axis = 1)) #columnwise

98
[[ 3  7 12]
 [ 7  9 12]
 [14 13 21]]
[[14 22 25]
 [10  7 20]]


In [92]:
print(arr13)
print(arr13.min())
print(arr13.max())
print(np.where(arr13 > 8))

[[[ 1  3  5]
  [ 4  8  7]
  [ 9 11 13]]

 [[ 2  4  7]
  [ 3  1  5]
  [ 5  2  8]]]
1
13
(array([0, 0, 0]), array([2, 2, 2]), array([0, 1, 2]))


In [97]:
#where(0 - return index position for condiiton = true)
arr14 = np.arange(1,21).reshape(5,4)
print(arr14)
print(np.where(arr14 > 8))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
(array([2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [100]:
#statistical methods
arr15 = np.arange(1,37).reshape(6,6)
print(arr15.mean)               #calculate mean()
print(arr15.mean(axis = 0))     #calculate mean - rowwise
print(arr15.mean(axis = 1))     #calculate mean() - column wise

print(np.std(arr15))            # Standard deviation
print(np.var(arr15))            # variance


<built-in method mean of numpy.ndarray object at 0x0000022040802A90>
[16. 17. 18. 19. 20. 21.]
[ 3.5  9.5 15.5 21.5 27.5 33.5]
10.388294694831615
107.91666666666667


In [105]:
#array reverse
arr16 = np.arange(50)
print(arr16)
print("")
print(arr16[::-1])
print("")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


In [117]:
#flip
arr6 = np.arange(1,51).reshape(5,10)
print(arr6)

print("")
print(np.flip(arr6))
print("")
print(np.flipud(arr6)) #flip up and down
print("")
print(np.fliplr(arr6)) #flip left and right


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

[[50 49 48 47 46 45 44 43 42 41]
 [40 39 38 37 36 35 34 33 32 31]
 [30 29 28 27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14 13 12 11]
 [10  9  8  7  6  5  4  3  2  1]]

[[41 42 43 44 45 46 47 48 49 50]
 [31 32 33 34 35 36 37 38 39 40]
 [21 22 23 24 25 26 27 28 29 30]
 [11 12 13 14 15 16 17 18 19 20]
 [ 1  2  3  4  5  6  7  8  9 10]]

[[10  9  8  7  6  5  4  3  2  1]
 [20 19 18 17 16 15 14 13 12 11]
 [30 29 28 27 26 25 24 23 22 21]
 [40 39 38 37 36 35 34 33 32 31]
 [50 49 48 47 46 45 44 43 42 41]]


In [127]:

#Flatten - to convert n-d array into 1-D array
arr17 = np.random.randint(10,50, size = (5,3))
print(arr17)
print(" ")
# 2_d array into 1D array
print(arr17.flatten())
print(" ")
#Ravel() - Flattens N-D array to 1D array
print(arr17.ravel())

[[25 41 14]
 [33 42 21]
 [43 40 38]
 [30 31 11]
 [22 35 14]]
 
[25 41 14 33 42 21 43 40 38 30 31 11 22 35 14]
 
[25 41 14 33 42 21 43 40 38 30 31 11 22 35 14]


In [128]:
#np.argmax() - Returns Index position of Maximum value along axis.
print(np.argmax(arr17))

6
